In [0]:
from faker import Faker
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

fake = Faker("en_IN")

random.seed(42)
np.random.seed(42)

In [0]:
cities = [
    ("Delhi", "Delhi"),
    ("Mumbai", "Maharashtra"),
    ("Bangalore", "Karnataka"),
    ("Chennai", "Tamil Nadu"),
    ("Hyderabad", "Telangana"),
    ("Kolkata", "West Bengal"),
    ("Pune", "Maharashtra"),
    ("Lucknow", "Uttar Pradesh")
]

customers = []

for i in range(1,1001):

    city,state=random.choice(cities)

    customers.append({
        "customer_id":i,
        "customer_name":fake.name(),
        "city":city,
        "state":state,
        "phone":fake.phone_number(),
        "email":fake.email()
    })

customers_df=pd.DataFrame(customers)

customers_df.to_csv(
"/Volumes/workspace/default/fmcg_data/customers.csv",
index=False
)

customers_df.head()

   customer_id      customer_name  ...        phone                    email
0            1   Jagrati Chandran  ...  04404791098  madhavbarad@example.net
1            2     Urvashi D’Alia  ...  09635347969     dayita79@example.org
2            3   Vaishnavi Sangha  ...  01344413931        mhans@example.net
3            4        Tarak Vohra  ...  05820557775        omuni@example.org
4            5  Aarna Padmanabhan  ...  03031426421      leena07@example.net

[5 rows x 6 columns]

In [0]:
categories = [
    "Beverages",
    "Snacks",
    "Personal Care",
    "Household",
    "Dairy"
]

brands = [
    "Nestle",
    "Dabur",
    "HUL",
    "ITC",
    "Parle",
    "Amul"
]

products=[]

for i in range(1,501):

    category=random.choice(categories)

    products.append({
        "product_id":i,
        "product_name":fake.word().capitalize(),
        "category":category,
        "brand":random.choice(brands),
        "price":round(random.uniform(20,500),2)
    })

products_df=pd.DataFrame(products)

products_df.to_csv(
"/Volumes/workspace/default/fmcg_data/products.csv",
index=False
)

products_df.head()

   product_id product_name   category   brand   price
0           1         Iure      Dairy  Nestle  236.96
1           2      Ratione     Snacks   Parle   40.82
2           3   Distinctio      Dairy     HUL  239.86
3           4          Vel  Beverages  Nestle  499.32
4           5        Saepe  Household     ITC  349.33

In [0]:
stores=[]

for i in range(1,101):

    city,state=random.choice(cities)

    stores.append({
        "store_id":i,
        "store_name":"Store_"+str(i),
        "city":city,
        "state":state
    })

stores_df=pd.DataFrame(stores)

stores_df.to_csv(
"/Volumes/workspace/default/fmcg_data/stores.csv",
index=False
)

stores_df.head()

   store_id store_name       city          state
0         1    Store_1       Pune    Maharashtra
1         2    Store_2    Lucknow  Uttar Pradesh
2         3    Store_3  Bangalore      Karnataka
3         4    Store_4  Hyderabad      Telangana
4         5    Store_5    Chennai     Tamil Nadu

In [0]:
sales=[]

for i in range(1,10001):

    quantity=random.randint(1,10)

    price=random.uniform(20,500)

    sales.append({

        "sale_id":i,

        "customer_id":random.randint(1,1000),

        "product_id":random.randint(1,500),

        "store_id":random.randint(1,100),

        "quantity":quantity,

        "amount":round(quantity*price,2),

        "sale_date":fake.date_between(
            start_date="-2y",
            end_date="today"
        )

    })

sales_df=pd.DataFrame(sales)

sales_df.to_csv(
"/Volumes/workspace/default/fmcg_data/sales.csv",
index=False
)

sales_df.head()

   sale_id  customer_id  product_id  store_id  quantity   amount   sale_date
0        1          661         477        23         9  3175.63  2026-05-30
1        2          296          72        24         9   900.86  2025-04-27
2        3          635          28        46         6  2544.92  2025-09-20
3        4          200         418        50         1   252.61  2024-09-05
4        5          507         210        88         9  2363.49  2024-07-25

In [0]:
inventory=[]

for product in range(1,501):

    inventory.append({
        "product_id":product,
        "stock":random.randint(20,500)
    })

inventory_df=pd.DataFrame(inventory)

inventory_df.to_csv(
"/Volumes/workspace/default/fmcg_data/inventory.csv",
index=False
)

inventory_df.head()

   product_id  stock
0           1    432
1           2    186
2           3    290
3           4    249
4           5     97

In [0]:
promotions=[]

for i in range(1,101):

    start=fake.date_between("-1y","today")
    end=start+timedelta(days=30)

    promotions.append({

        "promotion_id":i,

        "product_id":random.randint(1,500),

        "discount":random.choice([5,10,15,20,25,30]),

        "start_date":start,

        "end_date":end

    })

promotions_df=pd.DataFrame(promotions)

promotions_df.to_csv(
"/Volumes/workspace/default/fmcg_data/promotions.csv",
index=False
)

promotions_df.head()

   promotion_id  product_id  discount  start_date    end_date
0             1         315        15  2025-08-02  2025-09-01
1             2         467        25  2025-11-01  2025-12-01
2             3         407        25  2026-05-23  2026-06-22
3             4         441         5  2025-12-04  2026-01-03
4             5         298        30  2026-06-22  2026-07-22

In [0]:
customers = pd.read_csv("/Volumes/workspace/default/fmcg_data/customers.csv")
products = pd.read_csv("/Volumes/workspace/default/fmcg_data/products.csv")
stores = pd.read_csv("/Volumes/workspace/default/fmcg_data/stores.csv")
sales = pd.read_csv("/Volumes/workspace/default/fmcg_data/sales.csv")

print("Customers :", customers.shape)
print("Products  :", products.shape)
print("Stores    :", stores.shape)
print("Sales     :", sales.shape)

Customers : (1000, 6)
Products  : (500, 5)
Stores    : (100, 4)
Sales     : (10000, 7)

In [0]:
# Introduce data quality issues

# Duplicate customers
customers_dirty = pd.concat([customers_df, customers_df.iloc[:20]], ignore_index=True)

# Missing emails
customers_dirty.loc[
    customers_dirty.sample(25, random_state=42).index,
    "email"
] = None

# Inconsistent city names
customers_dirty["city"] = customers_dirty["city"].replace({
    "Delhi":"delhi",
    "Mumbai":"MUMBAI",
    "Bangalore":"bangalore"
})

customers_dirty.to_csv(
"/Volumes/workspace/default/fmcg_data/customers_dirty.csv",
index=False
)

print(customers_dirty.shape)

(1020, 6)

In [0]:
sales_dirty = sales_df.copy()

# Invalid quantities
sales_dirty.loc[
    sales_dirty.sample(30, random_state=10).index,
    "quantity"
] = -5

# Missing Amount
sales_dirty.loc[
    sales_dirty.sample(25, random_state=20).index,
    "amount"
] = None

# Duplicate records
sales_dirty = pd.concat(
    [sales_dirty, sales_dirty.iloc[:50]],
    ignore_index=True
)

sales_dirty.to_csv(
"/Volumes/workspace/default/fmcg_data/sales_dirty.csv",
index=False
)

print(sales_dirty.shape)

(10050, 7)